  name: BrowserStack Web Tests

  on:
   workflow_dispatch:
     inputs:
       message:
         description: 'Message for manually triggering'
         required: false
         default: 'Triggered for Updates'
         type: string
   push:
     branches:
       - '!release-branch'
       - release*
       - master
       - 1.*
       - develop
    
  jobs:
    inji-web-test:
      runs-on: ubuntu-latest
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup ufw firewall
        run: |
          sudo ufw enable
          sudo ufw allow ssh
          sudo ufw allow 51820/udp
          sudo ufw status

      - name: Install WireGuard
        run: sudo apt-get install -y wireguard

      - name: Configure WireGuard
        run: |
          echo "${{ secrets.CLUSTER_WIREGUARD }}" | sudo tee /etc/wireguard/wg0.conf

      - name: Start WireGuard
        run: |
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo chmod 700 /etc/wireguard/
          sudo chmod 644 /lib/systemd/system/wg-quick@.service
          sudo systemctl daemon-reload
          sudo wg-quick up wg0
          sudo wg show wg0          
    
      - name: Run tests
        run: |
           cd inji-web-test
           mvn clean test -DtestngXmlFile="TestNg.xml"

      - name: Save test reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-reports
          path: inji-web-test/test-output         

    upload-to-s3:
      runs-on: ubuntu-latest
      needs: inji-web-test
      if: always()
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1" # Specify your AWS region
          S3_BUCKET: "inji-stack" # Replace with your S3 bucket name
          S3_OBJECT_KEY: "inji-web" # Replace with your desired object key (e.g., folder structure)
        run: |
          aws s3 cp inji-web-test/test-output/test-reports s3://$S3_BUCKET/$S3_OBJECT_KEY/ --recursive          
